### 1 Importando os dados

In [1]:
import pandas as pd

df = pd.read_csv(r'C:\Users\Pedro\Desktop\Estudos\Databases\FIFA19.csv', sep=',', encoding ='utf8')
df.head()

,Unnamed: 0,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,League,Speciality
0,0,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,Left,...,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M,LALIGA SANTANDER,Complete Forward
1,1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,Right,...,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M,SERIE A TIM,Distance Shooter
2,2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,Right,...,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M,LIGUE 1 CONFORAMA,Complete Forward
3,3,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,Right,...,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M,PREMIER LEAGUE,Goalkeeper
4,4,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,Right,...,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M,PREMIER LEAGUE,Complete Midfielder

### Informações sobre o dataset

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18147 entries, 0 to 18146
Data columns (total 58 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                18147 non-null  int64
 1   Name                      18147 non-null  object
 2   Age                       18147 non-null  int64
 3   Nationality               18147 non-null  object
 4   Overall                   18147 non-null  int64
 5   Potential                 18147 non-null  int64
 6   Club                      18147 non-null  object
 7   Value                     18147 non-null  object
 8   Wage                      18147 non-null  object
 9   Preferred Foot            18147 non-null  object
 10  International Reputation  18147 non-null  float64
 11  Weak Foot                 18147 non-null  float64
 12  Skill Moves               18147 non-null  float64
 13  Work Rate                 18147 non-null  object
 14  Position                  18147 non-null  object
 15  Jersey Number             18147 non-null  float64
 16  Joined                    16654 non-null  object
 17  Loaned From               18147 non-null  object
 18  Contract Valid Until      18147 non-null  object
 19  Height                    18147 non-null  object
 20  Weight                    18147 non-null  object
 21  Crossing                  18147 non-null  float64
 22  Finishing                 18147 non-null  float64
 23  HeadingAccuracy           18147 non-null  float64
 24  ShortPassing              18147 non-null  float64
 25  Volleys                   18147 non-null  float64
 26  Dribbling                 18147 non-null  float64
 27  Curve                     18147 non-null  float64
 28  FKAccuracy                18147 non-null  float64
 29  LongPassing               18147 non-null  float64
 30  BallControl               18147 non-null  float64
 31  Acceleration              18147 non-null  float64
 32  SprintSpeed               18147 non-null  float64
 33  Agility                   18147 non-null  float64
 34  Reactions                 18147 non-null  float64
 35  Balance                   18147 non-null  float64
 36  ShotPower                 18147 non-null  float64
 37  Jumping                   18147 non-null  float64
 38  Stamina                   18147 non-null  float64
 39  Strength                  18147 non-null  float64
 40  LongShots                 18147 non-null  float64
 41  Aggression                18147 non-null  float64
 42  Interceptions             18147 non-null  float64
 43  Positioning               18147 non-null  float64
 44  Vision                    18147 non-null  float64
 45  Penalties                 18147 non-null  float64
 46  Composure                 18147 non-null  float64
 47  Marking                   18147 non-null  float64
 48  StandingTackle            18147 non-null  float64
 49  SlidingTackle             18147 non-null  float64
 50  GKDiving                  18147 non-null  float64
 51  GKHandling                18147 non-null  float64
 52  GKKicking                 18147 non-null  float64
 53  GKPositioning             18147 non-null  float64
 54  GKReflexes                18147 non-null  float64
 55  Release Clause            18147 non-null  object
 56  League                    18147 non-null  object
 57  Speciality                18147 non-null  object
dtypes: float64(38), int64(4), object(16)
memory usage: 8.0+ MB

In [3]:
df.shape
print('temos %0.f linhas e %0.f colunas no dataset.' %(df.shape[0], df.shape[1]))

temos 18147 linhas e 58 colunas no dataset.

### 2. Filtrando dados

In [6]:
df.loc[0:5, 'Name']

0             L. Messi
1    Cristiano Ronaldo
2            Neymar Jr
3               De Gea
4         K. De Bruyne
5            E. Hazard
Name: Name, dtype: object

In [11]:
# utilizandoo o LOC e especificando algumas colunas
df.loc[0:6, ['Name', 'Potential', 'Age']]

                Name  Potential  Age
0           L. Messi         94   31
1  Cristiano Ronaldo         94   33
2          Neymar Jr         93   26
3             De Gea         93   27
4       K. De Bruyne         92   27
5          E. Hazard         91   27
6          L. Modrić         91   32

In [15]:
# Utilizando o ILOC e selecionando o intervalo de linhas e colunas

df.iloc[0:10, 0:7]

,Unnamed: 0,Name,Age,Nationality,Overall,Potential,Club
0,0,L. Messi,31,Argentina,94,94,FC Barcelona
1,1,Cristiano Ronaldo,33,Portugal,94,94,Juventus
2,2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain
3,3,De Gea,27,Spain,91,93,Manchester United
4,4,K. De Bruyne,27,Belgium,91,92,Manchester City
5,5,E. Hazard,27,Belgium,91,91,Chelsea
6,6,L. Modrić,32,Croatia,91,91,Real Madrid
7,7,L. Suárez,31,Uruguay,91,91,FC Barcelona
8,8,Sergio Ramos,32,Spain,91,91,Real Madrid
9,9,J. Oblak,25,Slovenia,90,93,Atlético Madrid

In [18]:
# Filtrando com base em uma expressão

df.loc[df['Age'] <= 18].head(5)

,Unnamed: 0,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,League,Speciality
226,226,M. de Ligt,18,Netherlands,82,91,Ajax,€27M,€11K,Right,...,84.0,79.0,12.0,11.0,11.0,12.0,10.0,€43.2M,EREDIVISIE,Strength
1004,1004,J. Sancho,18,England,77,89,Borussia Dortmund,€14.5M,€22K,Right,...,33.0,36.0,7.0,11.0,10.0,11.0,13.0,€27.6M,BUNDESLIGA,No Speciality
1143,1143,Vinícius Júnior,17,Brazil,77,92,Real Madrid,€17.5M,€66K,Right,...,25.0,18.0,5.0,7.0,7.0,7.0,10.0,€46.8M,LALIGA SANTANDER,Speedster
1800,1800,R. Sessegnon,18,England,75,88,Fulham,€12M,€27K,Left,...,68.0,62.0,6.0,11.0,7.0,8.0,7.0,€30.3M,PREMIER LEAGUE,No Speciality
2640,2640,G. Chakvetadze,18,Georgia,73,86,KAA Gent,€7M,€10K,Right,...,41.0,32.0,10.0,8.0,13.0,8.0,13.0,€14.9M,PRO LEAGUE,No Speciality

In [20]:
# Filtrando com o filter
df.filter(['Name', 'Age', 'Nationality'])

                     Name  Age Nationality
0                L. Messi   31   Argentina
1       Cristiano Ronaldo   33    Portugal
2               Neymar Jr   26      Brazil
3                  De Gea   27       Spain
4            K. De Bruyne   27     Belgium
...                   ...  ...         ...
18142        J. Lundstram   19     England
18143  N. Christoffersson   19      Sweden
18144           B. Worman   16     England
18145      D. Walker-Rice   17     England
18146           G. Nugent   16     England

[18147 rows x 3 columns]

In [36]:
# filtrando com base na média da idade dos jogadores

media_age = df['Age'].mean()
print(media_age)
# Usando o LOC
df.loc[df['Age'] <= media_age].head(5)

25.12112194853144

,Unnamed: 0,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,League,Speciality
9,9,J. Oblak,25,Slovenia,90,93,Atlético Madrid,€68M,€94K,Right,...,12.0,18.0,86.0,92.0,78.0,88.0,89.0,€144.5M,LALIGA SANTANDER,Goalkeeper
15,15,P. Dybala,24,Argentina,89,94,Juventus,€89M,€205K,Left,...,20.0,20.0,5.0,4.0,4.0,5.0,8.0,€153.5M,SERIE A TIM,Complete Midfielder
16,16,H. Kane,24,England,89,91,Tottenham Hotspur,€83.5M,€205K,Right,...,36.0,38.0,8.0,10.0,11.0,14.0,11.0,€160.7M,PREMIER LEAGUE,Clinical Finisher
25,25,K. Mbappé,19,France,88,95,Paris Saint-Germain,€81M,€100K,Right,...,34.0,32.0,13.0,5.0,7.0,11.0,6.0,€166.1M,LIGUE 1 CONFORAMA,Dribbler
42,42,S. Umtiti,24,France,87,92,FC Barcelona,€57M,€205K,Left,...,89.0,86.0,15.0,10.0,14.0,12.0,15.0,€121.1M,LALIGA SANTANDER,Tackler

In [37]:
# Usando o QUERY
df.query('Age <= @media_age').head(5) ## utilizo o @ pois a variavel vem de fora do dataset

,Unnamed: 0,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,League,Speciality
9,9,J. Oblak,25,Slovenia,90,93,Atlético Madrid,€68M,€94K,Right,...,12.0,18.0,86.0,92.0,78.0,88.0,89.0,€144.5M,LALIGA SANTANDER,Goalkeeper
15,15,P. Dybala,24,Argentina,89,94,Juventus,€89M,€205K,Left,...,20.0,20.0,5.0,4.0,4.0,5.0,8.0,€153.5M,SERIE A TIM,Complete Midfielder
16,16,H. Kane,24,England,89,91,Tottenham Hotspur,€83.5M,€205K,Right,...,36.0,38.0,8.0,10.0,11.0,14.0,11.0,€160.7M,PREMIER LEAGUE,Clinical Finisher
25,25,K. Mbappé,19,France,88,95,Paris Saint-Germain,€81M,€100K,Right,...,34.0,32.0,13.0,5.0,7.0,11.0,6.0,€166.1M,LIGUE 1 CONFORAMA,Dribbler
42,42,S. Umtiti,24,France,87,92,FC Barcelona,€57M,€205K,Left,...,89.0,86.0,15.0,10.0,14.0,12.0,15.0,€121.1M,LALIGA SANTANDER,Tackler

In [48]:
# Filtragem contendo uma lista de valores
df_nacional =  df[df['Nationality'].isin(['Brazil'])]
df_nacional.head()

,Unnamed: 0,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,League,Speciality
2,2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,Right,...,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M,LIGUE 1 CONFORAMA,Complete Forward
27,27,Casemiro,26,Brazil,88,90,Real Madrid,€59.5M,€285K,Right,...,90.0,87.0,13.0,14.0,16.0,12.0,12.0,€126.4M,LALIGA SANTANDER,Complete Defender
32,32,Coutinho,26,Brazil,88,89,FC Barcelona,€69.5M,€340K,Right,...,54.0,47.0,12.0,7.0,9.0,14.0,6.0,€147.7M,LALIGA SANTANDER,Complete Midfielder
35,35,Marcelo,30,Brazil,88,88,Real Madrid,€43M,€285K,Left,...,85.0,86.0,12.0,5.0,5.0,5.0,9.0,€88.2M,LALIGA SANTANDER,Dribbler
39,39,Thiago Silva,33,Brazil,88,88,Paris Saint-Germain,€24M,€165K,Right,...,89.0,85.0,9.0,12.0,5.0,9.0,10.0,€44.4M,LIGUE 1 CONFORAMA,Tactician

In [49]:
# Filtragem comparando valores
df_comp = df[df['Potential'] == df['Overall']]
df_comp.head()

,Unnamed: 0,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,League,Speciality
0,0,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,Left,...,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M,LALIGA SANTANDER,Complete Forward
1,1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,Right,...,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M,SERIE A TIM,Distance Shooter
5,5,E. Hazard,27,Belgium,91,91,Chelsea,€93M,€340K,Right,...,27.0,22.0,11.0,12.0,6.0,8.0,8.0,€172.1M,PREMIER LEAGUE,Complete Midfielder
6,6,L. Modrić,32,Croatia,91,91,Real Madrid,€67M,€420K,Right,...,76.0,73.0,13.0,9.0,7.0,14.0,9.0,€137.4M,LALIGA SANTANDER,Complete Midfielder
7,7,L. Suárez,31,Uruguay,91,91,FC Barcelona,€80M,€455K,Right,...,45.0,38.0,27.0,25.0,31.0,33.0,37.0,€164M,LALIGA SANTANDER,Complete Forward

In [56]:
# Filtrando colunas númericas

numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

df.numerics = df.select_dtypes(exclude = numerics) # posso utilizar o include aqui também
df.numerics.head()

,Name,Nationality,Club,Value,Wage,Preferred Foot,Work Rate,Position,Joined,Loaned From,Contract Valid Until,Height,Weight,Release Clause,League,Speciality
0,L. Messi,Argentina,FC Barcelona,€110.5M,€565K,Left,Medium/ Medium,RF,"Jul 1, 2004",Not on loan,2021,5'7,159lbs,€226.5M,LALIGA SANTANDER,Complete Forward
1,Cristiano Ronaldo,Portugal,Juventus,€77M,€405K,Right,High/ Low,ST,"Jul 10, 2018",Not on loan,2022,6'2,183lbs,€127.1M,SERIE A TIM,Distance Shooter
2,Neymar Jr,Brazil,Paris Saint-Germain,€118.5M,€290K,Right,High/ Medium,LW,"Aug 3, 2017",Not on loan,2022,5'9,150lbs,€228.1M,LIGUE 1 CONFORAMA,Complete Forward
3,De Gea,Spain,Manchester United,€72M,€260K,Right,Medium/ Medium,GK,"Jul 1, 2011",Not on loan,2020,6'4,168lbs,€138.6M,PREMIER LEAGUE,Goalkeeper
4,K. De Bruyne,Belgium,Manchester City,€102M,€355K,Right,High/ High,RCM,"Aug 30, 2015",Not on loan,2023,5'11,154lbs,€196.4M,PREMIER LEAGUE,Complete Midfielder

In [63]:
# filtrando com scripts em SQL
# pip install pandasql -- instalar a biblioteca 
import pandasql as ps

query = """ SELECT * FROM df_nacional
           WHERE Age >=30 """
ps.sqldf(query,locals())

,Unnamed: 0,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,League,Speciality
0,35,Marcelo,30,Brazil,88,88,Real Madrid,€43M,€285K,Left,...,85.0,86.0,12.0,5.0,5.0,5.0,9.0,€88.2M,LALIGA SANTANDER,Dribbler
1,39,Thiago Silva,33,Brazil,88,88,Paris Saint-Germain,€24M,€165K,Right,...,89.0,85.0,9.0,12.0,5.0,9.0,10.0,€44.4M,LIGUE 1 CONFORAMA,Tactician
2,75,Fernandinho,33,Brazil,86,86,Manchester City,€18M,€185K,Right,...,85.0,80.0,12.0,11.0,5.0,13.0,7.0,€33.3M,PREMIER LEAGUE,Tactician
3,102,Naldo,35,Brazil,85,85,FC Schalke 04,€9M,€38K,Right,...,88.0,85.0,14.0,10.0,14.0,8.0,14.0,€15.3M,BUNDESLIGA,No Speciality
4,104,Miranda,33,Brazil,85,85,Inter,€15.5M,€96K,Right,...,90.0,85.0,12.0,6.0,10.0,13.0,12.0,€26.4M,SERIE A TIM,No Speciality
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,12561,André Luis Neitzke,31,Brazil,63,63,FC Sion,€250K,€5K,Right,...,67.0,66.0,6.0,7.0,10.0,8.0,10.0,€363K,RAIFFEISEN SUPER LEAGUE,No Speciality
310,12607,Felipe Soldivia,30,Brazil,63,63,Ceará Sporting Club,€350K,€4K,Right,...,53.0,35.0,8.0,14.0,13.0,6.0,10.0,€648K,0,No Speciality
311,13094,Túlio Nevinha,30,Brazil,62,62,Ceará Sporting Club,€230K,€3K,Right,...,63.0,54.0,10.0,13.0,17.0,12.0,14.0,€426K,0,No Speciality
312,13477,Tiagildo Serra,30,Brazil,62,62,Sport Club do Recife,€290K,€3K,Left,...,23.0,25.0,16.0,18.0,10.0,15.0,13.0,€551K,0,No Speciality
313,14411,Marcus Vinícius,34,Brazil,61,61,Arka Gdynia,€130K,€1K,Right,...,51.0,42.0,16.0,12.0,10.0,13.0,15.0,€176K,EKSTRAKLASA,No Speciality