### Tratando dataframes

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\Pedro\Desktop\Estudos\Databases\FIFA19.csv', sep=',', encoding='utf-8')
df.head()

,Unnamed: 0,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,League,Speciality
0,0,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,Left,...,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M,LALIGA SANTANDER,Complete Forward
1,1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,Right,...,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M,SERIE A TIM,Distance Shooter
2,2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,Right,...,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M,LIGUE 1 CONFORAMA,Complete Forward
3,3,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,Right,...,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M,PREMIER LEAGUE,Goalkeeper
4,4,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,Right,...,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M,PREMIER LEAGUE,Complete Midfielder

Vamos começar tratando o campo Value e Wage que estão no tipo object, mas quero em formato numérico.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18147 entries, 0 to 18146
Data columns (total 58 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                18147 non-null  int64
 1   Name                      18147 non-null  object
 2   Age                       18147 non-null  int64
 3   Nationality               18147 non-null  object
 4   Overall                   18147 non-null  int64
 5   Potential                 18147 non-null  int64
 6   Club                      18147 non-null  object
 7   Value                     18147 non-null  object
 8   Wage                      18147 non-null  object
 9   Preferred Foot            18147 non-null  object
 10  International Reputation  18147 non-null  float64
 11  Weak Foot                 18147 non-null  float64
 12  Skill Moves               18147 non-null  float64
 13  Work Rate                 18147 non-null  object
 14  Position                  18147 non-null  object
 15  Jersey Number             18147 non-null  float64
 16  Joined                    16654 non-null  object
 17  Loaned From               18147 non-null  object
 18  Contract Valid Until      18147 non-null  object
 19  Height                    18147 non-null  object
 20  Weight                    18147 non-null  object
 21  Crossing                  18147 non-null  float64
 22  Finishing                 18147 non-null  float64
 23  HeadingAccuracy           18147 non-null  float64
 24  ShortPassing              18147 non-null  float64
 25  Volleys                   18147 non-null  float64
 26  Dribbling                 18147 non-null  float64
 27  Curve                     18147 non-null  float64
 28  FKAccuracy                18147 non-null  float64
 29  LongPassing               18147 non-null  float64
 30  BallControl               18147 non-null  float64
 31  Acceleration              18147 non-null  float64
 32  SprintSpeed               18147 non-null  float64
 33  Agility                   18147 non-null  float64
 34  Reactions                 18147 non-null  float64
 35  Balance                   18147 non-null  float64
 36  ShotPower                 18147 non-null  float64
 37  Jumping                   18147 non-null  float64
 38  Stamina                   18147 non-null  float64
 39  Strength                  18147 non-null  float64
 40  LongShots                 18147 non-null  float64
 41  Aggression                18147 non-null  float64
 42  Interceptions             18147 non-null  float64
 43  Positioning               18147 non-null  float64
 44  Vision                    18147 non-null  float64
 45  Penalties                 18147 non-null  float64
 46  Composure                 18147 non-null  float64
 47  Marking                   18147 non-null  float64
 48  StandingTackle            18147 non-null  float64
 49  SlidingTackle             18147 non-null  float64
 50  GKDiving                  18147 non-null  float64
 51  GKHandling                18147 non-null  float64
 52  GKKicking                 18147 non-null  float64
 53  GKPositioning             18147 non-null  float64
 54  GKReflexes                18147 non-null  float64
 55  Release Clause            18147 non-null  object
 56  League                    18147 non-null  object
 57  Speciality                18147 non-null  object
dtypes: float64(38), int64(4), object(16)
memory usage: 8.0+ MB

In [4]:
## Nesse caso não contém valores nulos nas colunas mas por precaução vamos eliminar os nulos
df_value = df['Value'].fillna('0', inplace = True) 
df_wage = df['Wage'].fillna('0', inplace = True)

In [5]:
# pegando o símbolo de euro e armazenando em uma varíavel

simbol_euro = df['Value'].values[0][0] #pegando o símbolo de euro e armazenando na varíavel
print(simbol_euro)

€

In [6]:
# Função para tratar os campos
def func_replace(value):
    valor_campo = value.replace(simbol_euro, '')
    if 'M' in valor_campo:
        valor_campo = valor_campo.replace('M', '') 
        return float(valor_campo)*1000000
    elif 'K' in valor_campo:
        valor_campo = valor_campo.replace('K', '')
        return float(valor_campo)*1000

In [7]:
 # Aplicando função
df['Value'] = df['Value'].apply(func_replace)
df['Wage'] = df['Wage'].apply(func_replace)

In [8]:
# Perceba que os campos foram tratados conforme a função
df.head()

,Unnamed: 0,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,League,Speciality
0,0,L. Messi,31,Argentina,94,94,FC Barcelona,110500000.0,565000.0,Left,...,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M,LALIGA SANTANDER,Complete Forward
1,1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000000.0,405000.0,Right,...,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M,SERIE A TIM,Distance Shooter
2,2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500000.0,290000.0,Right,...,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M,LIGUE 1 CONFORAMA,Complete Forward
3,3,De Gea,27,Spain,91,93,Manchester United,72000000.0,260000.0,Right,...,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M,PREMIER LEAGUE,Goalkeeper
4,4,K. De Bruyne,27,Belgium,91,92,Manchester City,102000000.0,355000.0,Right,...,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M,PREMIER LEAGUE,Complete Midfielder

In [9]:
# Tratando a coluna Release Clause com loops
release_clause = []

for valor_campo in df['Release Clause'].values:
    valor_sem_euro = valor_campo.replace(simbol_euro, '')
    if 'M' in valor_sem_euro:
        valor_sem_euro = float(valor_sem_euro.replace('M', '')) * 1000000
    elif 'K' in valor_sem_euro:
        valor_sem_euro = float(valor_sem_euro.replace('K', '')) *1000
    release_clause.append(valor_sem_euro)
df['Release Clause1'] = release_clause

In [10]:
# Coluna tratada com sucesso
df['Release Clause1'].head()

0    226500000.0
1    127100000.0
2    228100000.0
3    138600000.0
4    196400000.0
Name: Release Clause1, dtype: object